# Generated by Django 4.2.4 on 2023-12-08 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(default='Administrador', editable=False, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(default='Cliente', editable=False, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Entregado', 'ENTREGADO'), ('En camino', 'EN CAMINO')], max_length=45)),
                ('tipo_entrega', models.CharField(choices=[('Domicilio', 'DOMICILIO'), ('Retiro en Tienda', 'RETIRO EN TIENDA')], max_length=45)),
                ('precio', models.IntegerField()),
                ('Clientes_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Rotisería', 'ROTISERÍA'), ('Bebidas y Abarrotes', 'BEBIDAS Y ABARROTES'), ('Carnes', 'CARNES')], max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_has_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedidos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.pedidos')),
                ('Productos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.productos')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=150)),
                ('ccv', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('Clientes_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.clientes')),
                ('Pedidos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipal.pedidos')),
            ],
        ),
    ]
