# Generated by Django 4.2.4 on 2023-12-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_alter_pedidos_clientes_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_has_pedidos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
